---
brokerConfig:
  brokerSempUrl: https://mr-connection-6y32tpb05yv.messaging.solace.cloud:943
  username: pq-demo-admin
  password: 
  msgVpnName: pq-demo
  pollingInterval: 10
ecsServiceConfig:
- ecsCluster: hspencerCustomScalerSolaceClientCluster
  ecsService: hspenceCustomScalerSolaceClientService
  queueName: ecsQ2
  scalerBehaviorConfig:
    minReplicaCount: 1
    maxReplicaCount: 100
    messageCountTarget: 10
    messageReceiveRateTarget: 10
    messageSpoolUsageTarget: 100
    scaleOutConfig:
      maxScaleStep: 5
      cooldownPeriod: 60
      stabilizationWindow: 10
    scaleInConfig:
      maxScaleStep: 5
      cooldownPeriod: 60
      stabilizationWindow: 120